# This is the preferences file for Chem Manager.

[user]
version = "1.0"
late_minutes = 5.0  # If you are later than LATEMINUTES, you are tardy
start_date = "2026-02-02"    # Monday of first week of labs

